"""empty message

Revision ID: d0491c1172ce
Revises: e961a72604c6
Create Date: 2025-05-14 09:33:43.518822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0491c1172ce'
down_revision = 'e961a72604c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.alter_column('people_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planeta_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.alter_column('planeta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('people_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
